name: Bug
description: Submit if a decompiled symbol does not match the assembly from the game binary
title: "[BUG] "
labels: ["bug"]
assignees:
  - DeathHound6
body:
  - type: input
    id: symbol_address
    attributes:
      label: Symbol Address
      description: Enter the symbol's hex address that isn't correct
      placeholder: "803950E0"
    validations:
      required: true
  - type: textarea
    id: binary_asm
    attributes:
      label: Game Binary's Assembly
    validation:
      required: false
  - type: textarea
    id: decomp_asm
    attributes:
      label: Decompiled Assembly
    validation:
      required: false
