#ifndef ENGINE_CLASSES_CSPRORITYABASENODECLASSNAMENEXTUPDATABLELIFE_H
    #define ENGINE_CLASSES_CSPRORITYABASENODECLASSNAMENEXTUPDATABLELIFE_H

    template <typename T> class CSPriorityBaseNodeClassNameNextUpdatableLife {};

#endif
